kotlin.code.style=official
group=org.jetbrains.kotlin.compiler.plugin.template
version=0.1.0-SNAPSHOT
kotlin.compiler.plugin.devkit.minCliVersion=2.3.20
kotlin.compiler.plugin.devkit.includeBetaAndRc=latest
kotlin.compiler.plugin.devkit.minIdeaVersion=261
kotlin.compiler.plugin.devkit.includeIdeaRc=true
kotlin.compiler.plugin.devkit.includeIdeaEap=true
kotlin.compiler.plugin.devkit.useLatestDev=true
kotlin.compiler.plugin.devkit.compilerPlugin=compiler-plugin
kotlin.compiler.plugin.devkit.companionLibraries=plugin-annotations